// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1e3kwmP6JJ5INk0gE7UhOeCLWWrcGZE',
    appId: '1:939698795915:web:8cc2fc765b96ada22b2b8e',
    messagingSenderId: '939698795915',
    projectId: 'moni-clone',
    authDomain: 'moni-clone.firebaseapp.com',
    storageBucket: 'moni-clone.firebasestorage.app',
    measurementId: 'G-ENQJ6T32KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMF01XLGt6niwtISQ4tSh5kfjxuDf8ng',
    appId: '1:939698795915:android:2210e9b5e77e43af2b2b8e',
    messagingSenderId: '939698795915',
    projectId: 'moni-clone',
    storageBucket: 'moni-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1upQVzc9bbMZgA2yztUvzpOQF5_VIUlw',
    appId: '1:939698795915:ios:8974964790cb35b62b2b8e',
    messagingSenderId: '939698795915',
    projectId: 'moni-clone',
    storageBucket: 'moni-clone.firebasestorage.app',
    iosBundleId: 'com.moni-clone.moniClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1upQVzc9bbMZgA2yztUvzpOQF5_VIUlw',
    appId: '1:939698795915:ios:8974964790cb35b62b2b8e',
    messagingSenderId: '939698795915',
    projectId: 'moni-clone',
    storageBucket: 'moni-clone.firebasestorage.app',
    iosBundleId: 'com.moni-clone.moniClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf1e3kwmP6JJ5INk0gE7UhOeCLWWrcGZE',
    appId: '1:939698795915:web:e1d7da40ab4f5a232b2b8e',
    messagingSenderId: '939698795915',
    projectId: 'moni-clone',
    authDomain: 'moni-clone.firebaseapp.com',
    storageBucket: 'moni-clone.firebasestorage.app',
    measurementId: 'G-4L5LXW3GYX',
  );
}
